# Generated by Django 2.1.7 on 2019-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrygeneration',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
