# Generated by Django 2.1.7 on 2019-05-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_forecast', '0002_countryforecast_reference_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generationforecast',
            old_name='forecast',
            new_name='consumption_forecast',
        ),
        migrations.AddField(
            model_name='generationforecast',
            name='generation_forecast',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
