# Generated by Django 2.1.7 on 2019-04-21 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('last_updated', models.DateField(auto_now=True)),
                ('biomass', models.IntegerField(blank=True, default=0, null=True)),
                ('fossil_coal_derived_gas', models.IntegerField(blank=True, default=0, null=True)),
                ('fossil_gas', models.IntegerField(blank=True, default=0, null=True)),
                ('fossil_hard_coal', models.IntegerField(blank=True, default=0, null=True)),
                ('fossil_lignite', models.IntegerField(blank=True, default=0, null=True)),
                ('fossil_oil', models.IntegerField(blank=True, default=0, null=True)),
                ('fossil_oil_shale', models.IntegerField(blank=True, default=0, null=True)),
                ('fossil_peat', models.IntegerField(blank=True, default=0, null=True)),
                ('geothermal', models.IntegerField(blank=True, default=0, null=True)),
                ('hydro_pumped_storage', models.IntegerField(blank=True, default=0, null=True)),
                ('hydro_river_and_poundage', models.IntegerField(blank=True, default=0, null=True)),
                ('hydro_water_reservoir', models.IntegerField(blank=True, default=0, null=True)),
                ('marine', models.IntegerField(blank=True, default=0, null=True)),
                ('nuclear', models.IntegerField(blank=True, default=0, null=True)),
                ('other', models.IntegerField(blank=True, default=0, null=True)),
                ('other_renewable', models.IntegerField(blank=True, default=0, null=True)),
                ('solar', models.IntegerField(blank=True, default=0, null=True)),
                ('waste', models.IntegerField(blank=True, default=0, null=True)),
                ('wind_offshore', models.IntegerField(blank=True, default=0, null=True)),
                ('wind_onshore', models.IntegerField(blank=True, default=0, null=True)),
                ('total_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
            options={
                'verbose_name': 'Country Capacity',
                'verbose_name_plural': 'Countries Capacity',
                'ordering': ['country'],
            },
        ),
    ]
